import test from 'node:test';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { loadProject, digest, validateRegistry, validateTransition, affectedBy, evidenceGroups } from './long-game.mjs';
const production = loadProject(fileURLToPath(new URL('../', import.meta.url)));
// Synthetic fixtures are intentionally independent of the real chapter structure.
const sourceIds=['S01','S02','S06'];
const sources=sourceIds.map((id)=>({id,title:`Synthetic source ${id}`,url:`https://example.org/${id}`,access:'Synthetic test record',reviewedOn:'2026-09-24',status:'active',evidenceGroup:id,limitations:'Not scientific evidence.'}));
const entries=[['C01','finding','guideline-based',['S01'],[],false],['C02','finding','qualified',['S02'],[],false],['C06','finding','qualified',['S06'],[],false],['C07','finding','qualified',['S02'],[],false],['R02','synthesis','reasoned',['S01'],['C01','C02','C07'],true],['R03','synthesis','reasoned',['S06'],['C06'],true],['H01','hypothesis','unconfirmed',['S02'],['C02'],false]];
const claims=entries.map(([id,kind,confidence,refs,dependsOn,defaultAdvice])=>({id,kind,confidence,sources:refs,dependsOn,defaultAdvice,statement:`Synthetic ${id}`,population:'Test population',outcome:'Test outcome',limitations:'Test only.',reviewedOn:'2026-09-24',status:'active'}));
const chapters=[{slug:'priorities',claims:['C01','C02','C06']},{slug:'a-workable-week',claims:['C07','R02','R03']},{slug:'methods',claims:['H01']}].map((c)=>({...c,reviewedOn:'2026-09-24'}));
const documents=Object.fromEntries(chapters.map((c)=>[c.slug,c.claims.map((id)=>`[${id}](/guides/long-game/evidence/#${id})`).join(' ')]));
for (const c of chapters) c.contentSha256=digest(documents[c.slug]);
const initial={schemaVersion:1,version:'0.1.0',publishedOn:'2026-09-24',lastEdited:'2026-09-24',lastEvidenceReview:'2026-09-24',sources,claims,chapters};
const fixture = () => structuredClone(initial);
const reviewAll = (registry) => ({outcome:'published', reviewedClaims:registry.claims.map((c)=>c.id), reviewedChapters:registry.chapters.map((c)=>c.slug), confidenceChanges:[], heldRisks:[]});
test('foundation registry and visible citations are internally consistent', () => assert.deepEqual(validateRegistry(production.registry, production.documents), []));
test('a withdrawn protein source blocks the active foundation', () => { const r=fixture(); r.sources.find((s)=>s.id==='S06').status='withdrawn'; assert.match(validateRegistry(r,documents).join('\n'), /withdrawn source S06/); });
test('protein evidence change reaches the arithmetic and both reader chapters', () => { const impact=affectedBy(initial,{sources:['S06']}); assert.ok(impact.claims.includes('R03')); assert.ok(impact.chapters.includes('priorities')); assert.ok(impact.chapters.includes('a-workable-week')); });
test('a source conflict cannot publish after reviewing only its original claim', () => { const next=fixture(); next.version='0.1.1'; next.sources.find((s)=>s.id==='S06').limitations+=' New conflicting evidence requires reassessment.'; const result=validateTransition(initial,next,{outcome:'published',reviewedClaims:['C06'],reviewedChapters:[],confidenceChanges:[]}); assert.ok(result.some((x)=>x.includes('R03'))); assert.ok(result.some((x)=>x.includes('a-workable-week'))); });
test('an untested hypothesis cannot become default advice', () => { const r=fixture(); r.claims.find((c)=>c.id==='H01').defaultAdvice=true; assert.match(validateRegistry(r,documents).join('\n'), /hypothesis cannot be default/); });
test('default synthesis cannot launder a hypothesis through a dependency', () => { const r=fixture(); r.claims.find((c)=>c.id==='R02').dependsOn.push('H01'); assert.match(validateRegistry(r,documents).join('\n'), /default advice depends on untested hypothesis/); });
test('missing sources fail closed', () => { const r=fixture(); r.claims[0].sources=['S999']; assert.match(validateRegistry(r,documents).join('\n'), /unknown source S999/); });
test('dependency cycles are rejected', () => { const r=fixture(); r.claims.find((c)=>c.id==='C02').dependsOn=['R02']; assert.match(validateRegistry(r,documents).join('\n'), /Dependency cycle/); });
test('unregistered visible citation is detected even after fingerprinting', () => { const r=fixture(); const docs={...documents,priorities:documents.priorities+'\n[unsupported](/guides/long-game/evidence/#C999)\n'}; r.chapters[0].contentSha256=digest(docs.priorities); assert.match(validateRegistry(r,docs).join('\n'), /unregistered citation C999/); });
test('a chapter rewrite requires review even without an evidence change', () => { const r=fixture(); r.version='0.1.1'; r.chapters[0].contentSha256=digest('restructured chapter'); assert.match(validateTransition(initial,r,{reviewedClaims:[],reviewedChapters:[]}).join('\n'), /chapter review: priorities/); });
test('a confidence change needs an explicit rationale', () => { const r=fixture(); r.version='0.1.1'; r.claims.find((c)=>c.id==='C07').confidence='guideline-based'; assert.match(validateTransition(initial,r,reviewAll(r)).join('\n'), /Confidence changed without rationale: C07/); });
test('multiple reports in one evidence group count once', () => { const r=fixture(); r.sources[1].evidenceGroup=r.sources[0].evidenceGroup; assert.equal(evidenceGroups(r,['S01','S02']).length,1); });
test('a required expert review cannot be replaced by an empty field', () => { const r=fixture(); const c=r.claims.find((c)=>c.id==='R03'); c.requiresExpertReview=true; assert.match(validateRegistry(r,documents).join('\n'), /required expert review is missing/); });
test('a held release risk prevents publication', () => { const r=fixture(); assert.match(validateTransition(initial,r,{...reviewAll(r),heldRisks:['Unresolved safety-sensitive change']}).join('\n'), /Cannot publish/); });
test('a fully documented ordinary explanation revision can pass', () => { const r=fixture(); r.version='0.1.1'; r.claims.find((c)=>c.id==='R03').limitations+=' Clarified as arithmetic rather than a meal-timing claim.'; assert.deepEqual(validateTransition(initial,r,reviewAll(r)),[]); });
test('a no-change review does not demand invented content changes', () => assert.deepEqual(validateTransition(initial,fixture(),{outcome:'reviewed-no-change',reviewedClaims:[],reviewedChapters:[]}),[]));
