import { sources, topics, world } from './data.js';
export const escapeHTML = value => String(value).replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
export function renderTopic(topic) {
  return `<div class="mc-eyebrow">${escapeHTML(topic.category)}</div><h2>${escapeHTML(topic.title)}</h2>
    <p class="mc-intro">${escapeHTML(topic.intro)}</p><p>${escapeHTML(topic.body)}</p>
    <h3>Why it matters</h3><p>${escapeHTML(topic.why)}</p>
    <div class="mc-try"><span>TRY THIS</span><p>${escapeHTML(topic.try)}</p></div>
    <details class="mc-question"><summary>${escapeHTML(topic.question)}</summary><p>${escapeHTML(topic.answer)}</p></details>
    <div class="mc-related">${topic.related.map(id => `<button type="button" data-topic="${id}">${escapeHTML(topics.find(t => t.id === id).short)} <span aria-hidden="true">↗</span></button>`).join('')}</div>
    <div class="mc-sources"><h3>Go to the evidence</h3>${topic.sources.map(id => `<a href="${sources[id].url}" target="_blank" rel="noopener noreferrer">${escapeHTML(sources[id].title)} <span aria-hidden="true">↗</span></a>`).join('')}</div>`;
}
export function renderShell() {
  return `<div id="microcosm" class="mc-app">
  <a class="mc-skip" href="#mc-inspector">Skip the 3D explorer</a>
  <header class="mc-topbar"><a href="/" class="mc-home" aria-label="Return to Rough at Sea"><span aria-hidden="true">≈</span> ROUGH AT SEA</a><span class="mc-divider"></span><span class="mc-wordmark">microcosm</span><span class="mc-topnote">A world, one discovery at a time.</span><a class="mc-back" href="/">Back to the surface ↗</a></header>
  <main>
    <section class="mc-heading" aria-labelledby="mc-title"><div><div class="mc-eyebrow"><span class="mc-status-dot"></span> AN EVOLVING BIOLOGICAL WORLD <span class="mc-version">v${world.version}</span></div><h1 id="mc-title">Small cell.<em> Extraordinary world.</em></h1><p>Begin with a red blood cell. Look closer. There is more here than meets the eye.</p></div><button type="button" id="mc-tour-start" class="mc-primary">Take the guided tour <span aria-hidden="true">↗</span></button></section>
    <div class="mc-workspace">
      <section class="mc-explorer" aria-label="Interactive red blood cell explorer">
        <div class="mc-viewbar"><span class="mc-eyebrow">SPECIMEN 001 <span class="mc-mobile-hide">/ HUMAN BLOOD</span></span><div class="mc-segment" role="group" aria-label="Anatomical view"><button type="button" data-view="whole" aria-pressed="true">Whole cell</button><button type="button" data-view="inside" aria-pressed="false">Cutaway</button><button type="button" data-view="scaffold" aria-pressed="false">Scaffold</button></div></div>
        <div class="mc-stage" id="mc-stage"><canvas id="mc-canvas" tabindex="0" aria-label="Three-dimensional red blood cell. Drag to orbit, scroll to zoom. Keyboard arrows rotate; plus and minus zoom; R resets. Use the structure buttons below for accessible selection." aria-describedby="mc-controls-help"></canvas>
          <div class="mc-stage-title"><h2>Erythrocyte</h2><span>Mature human RBC · A, RhD-positive</span></div>
          <div id="mc-hotspots" class="mc-hotspots" aria-label="Structures in the 3D scene">${topics.filter(t => t.id !== 'no-nucleus').map(t => `<button type="button" data-topic="${t.id}" class="mc-hotspot" data-anchor="${t.id}" style="--marker:${t.color}" hidden><i></i>${escapeHTML(t.short)}</button>`).join('')}</div>
          <div class="mc-scale" id="mc-scale"><span id="mc-scale-line"></span><span id="mc-scale-text">Cell diameter ≈ 7.8 µm</span></div>
          <span class="mc-specimen-tag" id="mc-view-note">Surface markers enlarged</span>
          <div class="mc-loading" id="mc-render-status" role="status">Bringing a small world into focus…</div>
          <div id="mc-flight-pad" class="mc-flight-pad" hidden aria-label="Flight movement"><button type="button" data-move="w" aria-label="Fly forward">Forward</button><button type="button" data-move="s" aria-label="Fly backward">Back</button><button type="button" data-move="a" aria-label="Fly left">←</button><button type="button" data-move="d" aria-label="Fly right">→</button><button type="button" data-move="e" aria-label="Fly up">Rise</button><button type="button" data-move="q" aria-label="Fly down">Lower</button></div>
        </div>
        <div class="mc-camerabar"><div class="mc-segment" role="group" aria-label="Camera mode"><button type="button" data-camera="orbit" aria-pressed="true">Orbit</button><button type="button" data-camera="fly" aria-pressed="false">Free flight</button></div><div class="mc-camera-actions"><button type="button" id="mc-zoom-in" aria-label="Zoom in">＋</button><button type="button" id="mc-zoom-out" aria-label="Zoom out">−</button><button type="button" id="mc-reset">Reset view</button><button type="button" id="mc-spin" aria-pressed="false">Auto-orbit</button></div></div>
        <p class="mc-help" id="mc-controls-help">Drag to orbit · Scroll or pinch to zoom · Shift-drag to pan · Arrow keys rotate a focused canvas</p>
        <div class="mc-tools"><fieldset class="mc-layers"><legend>LAYERS</legend><label><input type="checkbox" id="mc-shell" checked> Membrane</label><label><input type="checkbox" id="mc-skeleton"> Skeleton</label><label><input type="checkbox" id="mc-hemoglobin"> Hemoglobin</label><label><input type="checkbox" id="mc-proteins" checked> Surface markers</label><label><input type="checkbox" id="mc-labels" checked> Labels</label></fieldset>
          <div class="mc-oxygen"><label for="mc-oxygenation">OXYGENATION <span>COLOR ILLUSTRATION</span></label><input id="mc-oxygenation" type="range" min="0" max="100" value="90" aria-valuetext="90 percent on an illustrative color scale, not a calculated saturation"><div><span>Less oxygenated</span><span>More oxygenated</span></div></div></div>
        <div class="mc-encounter-heading"><h2>Follow your curiosity</h2><span id="mc-progress" aria-live="polite">0 / ${topics.length} explored on this device</span></div><div class="mc-topic-list" aria-label="Explore a structure">${topics.map((t, i) => `<button type="button" data-topic="${t.id}" data-catalog="${t.id}" style="--marker:${t.color}" aria-pressed="false"><span class="mc-topic-number">${String(i + 1).padStart(2, '0')}</span><span>${escapeHTML(t.short)}</span><span class="mc-topic-check" aria-hidden="true">↗</span></button>`).join('')}</div>
      </section>
      <aside id="mc-inspector" class="mc-inspector" tabindex="-1" aria-label="Discovery notebook"><div class="mc-inspector-tabs" role="group" aria-label="Notebook section"><button type="button" data-panel="inspect" aria-pressed="true">Field notes</button><button type="button" data-panel="evolution" aria-pressed="false">Evolution <span class="mc-new-dot"></span></button></div>
        <div id="mc-tour" class="mc-tour" hidden><span id="mc-tour-position"></span><div><button type="button" id="mc-tour-prev" aria-label="Previous tour stop">←</button><button type="button" id="mc-tour-next">Next →</button><button type="button" id="mc-tour-end" aria-label="End guided tour">×</button></div></div>
        <div id="mc-inspect-panel"><div class="mc-notebook-meta"><span id="mc-note-index">ENCOUNTER 01</span><span>● FIELD NOTE</span></div><article id="mc-topic-content">${renderTopic(topics[0])}</article><p class="mc-select-hint">Select a marker in the scene or a structure in the index.</p></div>
        <div id="mc-evolution-panel" hidden><div class="mc-eyebrow">A PERSISTENT WORLD</div><h2>Built to grow.</h2><p>Each release adds to this world. A new cell will join the collection; it will not erase the cells you already know.</p>
          <h3>The collection</h3><div class="mc-collection">${world.cells.map((c, i) => `<div class="mc-cell ${c.status === 'available' ? 'is-available' : ''}"><span>${String(i + 1).padStart(2, '0')}</span><div><strong>${escapeHTML(c.title)}</strong><small>${escapeHTML(c.stage)}</small></div><span aria-hidden="true">${c.status === 'available' ? '●' : '○'}</span></div>`).join('')}</div>
          <h3>When does the next cell arrive?</h3><p>After the red cell reaches the following editorial milestones—not merely because a day has passed.</p><div class="mc-milestones">${world.milestones.map(m => `<div><span aria-label="${m.done ? 'Complete' : 'Planned'}">${m.done ? '✓' : '○'}</span><p><strong>${escapeHTML(m.title)}</strong><small>${escapeHTML(m.detail)}</small></p></div>`).join('')}</div>
          <h3>Release journal</h3>${world.releases.map(r => `<article class="mc-release"><span class="mc-eyebrow">${r.date} · v${r.version}</span><h4>${escapeHTML(r.title)}</h4><p>${escapeHTML(r.summary)}</p><small>${r.additions.length} encounters added · ${r.cell.toUpperCase()} retained</small></article>`).join('')}
          <p class="mc-automation-note">Daily publishing is not active yet. This journal records real published changes; it does not simulate progress with a countdown.</p></div>
      </aside>
    </div>
    <section class="mc-honesty" aria-labelledby="mc-model-title"><div><span class="mc-eyebrow">A MAP, NOT A MICROSCOPE</span><h2 id="mc-model-title">Know what you’re looking at.</h2></div><p>The cell shape is an idealized 3D model. Molecular sizes, counts, spacing, colors, and the regular skeleton mesh are exaggerated or simplified for learning. The cutaway is a viewing aid, not a ruptured cell. Oxygenation changes color only; no gas exchange, flow, or mechanical simulation is running. The scale marker applies to cell geometry, not the enlarged proteins.</p></section>
    <details class="mc-text-atlas"><summary>Read the complete text atlas · works without 3D or JavaScript</summary>${topics.map(t => `<article><h2>${escapeHTML(t.title)}</h2><p>${escapeHTML(t.intro)} ${escapeHTML(t.body)}</p><p>${escapeHTML(t.why)}</p><p>Sources: ${t.sources.map(s => `<a href="${sources[s].url}">${escapeHTML(sources[s].title)}</a>`).join(' · ')}</p></article>`).join('')}</details>
  </main><footer class="mc-footer"><a href="/">≈ Rough at Sea</a><span>One cell is only the beginning.</span><span>Educational exploration · Not a clinical tool</span></footer>
  <noscript><style>#mc-render-status { display:block } .mc-hotspots { display:none }</style><p class="mc-noscript">JavaScript is disabled. Open the complete text atlas above to explore every topic and source.</p></noscript>
  </div>`;
}
