export type Author = { id: string; name: string; born: number; died: number; start: number; end: number; note: string; source: string; works: [number, string][] };
export const authors: Author[] = [
{ id:'austen',name:'Jane Austen',born:1775,died:1817,start:1811,end:1817,note:'Novel publication span. Northanger Abbey and Persuasion appeared after her death in December 1817 (dated 1818 on their title pages). Her writing began much earlier.',source:'https://janeaustensociety.org.uk/jane-austen/biography/',works:[[1811,'Sense and Sensibility'],[1813,'Pride and Prejudice'],[1815,'Emma'],[1817,'Persuasion']]},
{ id:'shelley',name:'Mary Shelley',born:1797,died:1851,start:1818,end:1837,note:'Novel publication span, from Frankenstein to Falkner. Essays, editing and travel writing extend beyond this span.',source:'https://en.wikipedia.org/wiki/Mary_Shelley',works:[[1818,'Frankenstein'],[1826,'The Last Man'],[1837,'Falkner']]},
{ id:'dickens',name:'Charles Dickens',born:1812,died:1870,start:1836,end:1870,note:'Book publication span, from Sketches by Boz to the unfinished Mystery of Edwin Drood. Markers use first installment years for serialized novels.',source:'https://en.wikipedia.org/wiki/Charles_Dickens',works:[[1836,'The Pickwick Papers'],[1837,'Oliver Twist'],[1843,'A Christmas Carol'],[1859,'A Tale of Two Cities'],[1860,'Great Expectations'],[1870,'The Mystery of Edwin Drood']]},
{ id:'twain',name:'Mark Twain',born:1835,died:1910,start:1867,end:1909,note:'Book publication span, from The Celebrated Jumping Frog collection to Is Shakespeare Dead? Newspaper writing began earlier; posthumous books are excluded.',source:'https://en.wikipedia.org/wiki/Mark_Twain',works:[[1867,'The Celebrated Jumping Frog collection'],[1876,'The Adventures of Tom Sawyer'],[1884,'Adventures of Huckleberry Finn'],[1889,"A Connecticut Yankee in King Arthur’s Court"],[1909,'Is Shakespeare Dead?']]},
{ id:'tolkien',name:'J. R. R. Tolkien',born:1892,died:1973,start:1937,end:1967,note:'Selected fiction-book publication span, from The Hobbit to Smith of Wootton Major. Earlier poetry and scholarship are excluded; The Silmarillion appeared posthumously in 1977.',source:'https://en.wikipedia.org/wiki/J._R._R._Tolkien',works:[[1937,'The Hobbit'],[1954,'The Fellowship of the Ring'],[1955,'The Return of the King'],[1967,'Smith of Wootton Major']]},
{ id:'steinbeck',name:'John Steinbeck',born:1902,died:1968,start:1929,end:1966,note:'Book publication span, from Cup of Gold to America and Americans. Posthumous collections and unfinished works are excluded.',source:'https://www.steinbeckintheschools.com/authors-context/chronology',works:[[1929,'Cup of Gold'],[1935,'Tortilla Flat'],[1937,'Of Mice and Men'],[1939,'The Grapes of Wrath'],[1945,'Cannery Row'],[1952,'East of Eden'],[1961,'The Winter of Our Discontent'],[1966,'America and Americans']]},
{ id:'orwell',name:'George Orwell',born:1903,died:1950,start:1933,end:1949,note:'Book publication span, from Down and Out in Paris and London to Nineteen Eighty-Four. Journalism and earlier writing are not represented by the bar.',source:'https://en.wikipedia.org/wiki/George_Orwell',works:[[1933,'Down and Out in Paris and London'],[1936,'Keep the Aspidistra Flying'],[1945,'Animal Farm'],[1949,'Nineteen Eighty-Four']]},
{ id:'heinlein',name:'Robert A. Heinlein',born:1907,died:1988,start:1939,end:1987,note:'Professional fiction publication span, from the story Life-Line to To Sail Beyond the Sunset. For Us, the Living was written in 1938–39 but first published posthumously in 2003.',source:'https://sciencefiction.loa.org/biographies/heinlein.php',works:[[1939,'Life-Line'],[1947,'Rocket Ship Galileo'],[1951,'The Puppet Masters'],[1959,'Starship Troopers'],[1961,'Stranger in a Strange Land'],[1966,'The Moon Is a Harsh Mistress'],[1987,'To Sail Beyond the Sunset']]},
{ id:'vonnegut',name:'Kurt Vonnegut',born:1922,died:2007,start:1952,end:1997,note:'Novel publication span, from Player Piano to Timequake. Published stories began in 1950; essays and other books continued afterward.',source:'https://en.wikipedia.org/wiki/Kurt_Vonnegut',works:[[1952,'Player Piano'],[1963,'Cat’s Cradle'],[1969,'Slaughterhouse-Five'],[1973,'Breakfast of Champions'],[1997,'Timequake']]},
{ id:'leguin',name:'Ursula K. Le Guin',born:1929,died:2018,start:1966,end:2008,note:'Novel publication span, from Rocannon’s World to Lavinia. Poetry, stories and essays fall outside this span; it is not her full writing career.',source:'https://www.ursulakleguin.com/bibliography',works:[[1966,'Rocannon’s World'],[1968,'A Wizard of Earthsea'],[1969,'The Left Hand of Darkness'],[1974,'The Dispossessed'],[2008,'Lavinia']]},
{ id:'morrison',name:'Toni Morrison',born:1931,died:2019,start:1970,end:2015,note:'Novel publication span, from The Bluest Eye to God Help the Child. Editing, children’s books and nonfiction are excluded.',source:'https://guides.loc.gov/fiction-prize-toni-morrison/selected-bibliography',works:[[1970,'The Bluest Eye'],[1977,'Song of Solomon'],[1987,'Beloved'],[1992,'Jazz'],[2015,'God Help the Child']]},
{ id:'butler',name:'Octavia E. Butler',born:1947,died:2006,start:1976,end:2005,note:'Novel publication span, from Patternmaster to Fledgling. Short-fiction publication began earlier.',source:'https://www.octaviabutler.com/theauthor',works:[[1976,'Patternmaster'],[1979,'Kindred'],[1987,'Dawn'],[1993,'Parable of the Sower'],[1998,'Parable of the Talents'],[2005,'Fledgling']]},
];
